# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "47293c5d7e0a66694cae8b269ebdc9e2"
name = "corner-cart-Tushar"
application_url = "https://corner-cart-tushar.onrender.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://corner-cart-tushar.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
